public class MyClass {
  public static void main(String args[]) {
      //Membuat Variabel
 String Nama_saya;
 String Usia;
 Float Tbadan;
 
 //Membuat output
 Nama_saya = "Sawit sayang owo";
 Usia = "8 Bulan";
 Tbadan = 900.9f;
 System.out.println("Nama kamu : " + Nama_saya);
 System.out.println("Usia : " + Usia);
 System.out.println("Tinggi badan : " + Tbadan);
 
 System.out.println("Saya GILA sayang owo dan nyawit");
 
  }
}
